### ISSUE TITLE
Creating ontology ignores rdfs:comment field (small snafu....)

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/knora-api#1690] opened 2020-08-15 19:45 UTC
When creating an ontology with the API call:

```http://0.0.0.0:3333/v2/ontologies``` (POST)

and the body:
```json
{
  "knora-api:ontologyName" : "onto-with-comment",
  "knora-api:attachedToProject" : {
    "@id" : "http://rdfh.ch/projects/0001"
  },
  "rdfs:comments": "This comment does not arrive in Knora",
  "rdfs:label" : "Ontology with comment",
  "@context" : {
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#"
  }
}
```
the resulting ontology has no comment field, as the resulting json and subsequent queries show:
```
{
  "@id": "http://0.0.0.0:3333/ontology/0001/onto-with-comment/v2",
  "@type": "owl:Ontology",
  "knora-api:attachedToProject": {
    "@id": "http://rdfh.ch/projects/0001"
  },
  "knora-api:lastModificationDate": {
    "@type": "xsd:dateTimeStamp",
    "@value": "2020-08-15T19:40:27.566182Z"
  },
  "rdfs:label": "Ontology with comment",
  "@context": {
    "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#"
  }
}
```
Tests being made using postman...

**Comment by benjamingeer** [comment] 2020-08-15 19:58
I’m on holiday, please assign this to @SepidehAlassi

**Comment by subotic** [comment] 2020-08-15 22:25
@lrosenth and please open an issue on YouTrack. We don't use Github for issues anymore.

**Comment by SepidehAlassi** [comment] 2020-08-17 07:33
User story for this bug [DSP-548](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-46?p=110-4%2F111-29&issue=DSP-548)

**Comment by SepidehAlassi** [comment] 2020-08-17 08:06
@lrosenth when you request an ontology to be created, as a response, the metadata of the ontology is returned. Currently, the comment is not among the metadata information. I can add it though.

**Comment by lrosenth** [comment] 2020-08-17 08:17
Hey Sepideh,

Yes, this would be great. I thinbk (but I have to test) that the comment is also missing when querying the ontology.

THanks a lot,
Lukas (still lying on the back like a bug....)

Lukas Rosenthaler

Von meinem iPad gesendet

Am 17.08.2020 um 10:07 schrieb Sepideh Alassi <notifications@github.com>:

﻿

@lrosenth<https://github.com/lrosenth> when you request an ontology to be created, as a response, the metadata of the ontology is returned. Currently, the comment is not among the metadata information. I can add it though.

**Comment by SepidehAlassi** [comment] 2020-08-17 08:59
@lrosenth Having a closer look at the code, I figured out the following:

with the current design, comments can be given and are taken into account for ontology classes and properties but not for the ontology itself. Please see the example in the [documentation](https://docs.knora.org/03-apis/api-v2/ontology-information/#creating-a-new-ontology) 

The user can provide a comment for ontology, but it is currently ignored (not parsed out of the JSON-body of the request).

So an ontology comment is neither read during creation from the request nor stored, hence not returned. 

This issue is actually not a bug, it is a missing feature. It would need a bit more work than adding a field to the metadata. I will work on it first thing in the coming sprint.

**Comment by lrosenth** [comment] 2020-08-17 09:04
Ok, it‘s really not urgent at all!

Best,Lukas

Lukas Rosenthaler

Von meinem iPad gesendet

Am 17.08.2020 um 11:00 schrieb Sepideh Alassi <notifications@github.com>:

﻿

@lrosenth<https://github.com/lrosenth> Having a closer look at the code, I figured out the following:

with the current design, comments can be given and are taken into account for ontology classes and properties but not for the ontology itself. Please see the example in the documentation<https://docs.knora.org/03-apis/api-v2/ontology-information/#creating-a-new-ontology>

The user can provide a comment for ontology, but it is currently ignored (not parsed out of the JSON-body of the request).

So an ontology comment is neither read during creation from the request nor stored, hence not returned.

This issue is actually not a bug, it is a missing feature. It would need a bit more work than adding a field to the metadata. I will work on it first thing in the coming sprint.

**Closed** 2020-09-09 14:58 UTC
Labels: API/V2, enhancement, ontology
