### ISSUE TITLE
Upload issue using knora-py

### ISSUE THREAD

**Issue by EricSommerhalder** [dasch-swiss/knora-api#1605] opened 2020-02-25 10:26 UTC
While uploading data for the Portraits of Unbelonging- project with knora-py the error message below regularly shows up. The error happens when the upload is running smoothly and a lot of data already has been uploaded. When the database is cleared and the same upload requests are posted, no error is raised. I attach the trigs of the database, so the error can be reproduced. Also I'm attaching the user trigs to create the user with the permission to upload for the project. In the attached text file, there is the json that lead to the error when tried to upload. 
[attachments.zip](https://github.com/dasch-swiss/knora-api/files/4249355/attachments.zip)

 
_Traceback (most recent call last):
  File "/Users/eric/Develop/Portraits-of-Unbelonging/src/data_import_scripts/all_file_import.py", line 519, in <module>
    c. get_data_all_file(all_file)
  File "/Users/eric/Develop/Portraits-of-Unbelonging/src/data_import_scripts/all_file_import.py", line 74, in get_data_all_file
    j["photograph"]=self.create_pics_from_array(pictures_in_doc, lastname)
  File "/Users/eric/Develop/Portraits-of-Unbelonging/src/data_import_scripts/all_file_import.py", line 319, in create_pics_from_array
    j)['iri'])
  File "/Users/eric/Develop/knora-py/knora/knora.py", line 1520, in create_resource
    self.on_api_error(req)
  File "/Users/eric/Develop/knora-py/knora/knora.py", line 166, in on_api_error
    raise KnoraError("KNORA-ERROR: status code=" + str(res.status_code) + "\nMessage:" + res.text)
knora.KnoraError: KNORA-ERROR: status code=500
Message:{"knora-api:error":"org.knora.webapi.TriplestoreResponseException: Couldn't parse Turtle from triplestore","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
Exception ignored in: <function Knora.__del__ at 0x1102a5400>
Traceback (most recent call last):
  File "/Users/eric/Develop/knora-py/knora/knora.py", line 156, in __del__
  File "/Users/eric/Develop/knora-py/knora/knora.py", line 150, in logout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 158, in delete
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 60, in request
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 700, in merge_environment_settings
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/utils.py", line 761, in get_environ_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/utils.py", line 745, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2610, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2587, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2534, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down__

**Comment by benjamingeer** [comment] 2020-02-25 10:29
Could you also copy and paste the error from Knora's console log, showing the stack trace of the `TriplestoreResponseException`? We need the Scala stack trace output by the server, not the Python stack trace output by the client.

**Comment by EricSommerhalder** [comment] 2020-02-25 10:50
_api_1      | java.util.zip.ZipException: Not in GZIP format
api_1      | 	at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:69)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
api_1      | 	at java.base/java.io.InputStreamReader.read(Unknown Source)
api_1      | 	at java.base/java.io.Reader.read(Unknown Source)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:308)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getSparqlHttpResponse$1(HttpTriplestoreConnector.scala:664)
api_1      | 	at scala.util.Try$.apply(Try.scala:213)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:654)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:331)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$receive$1.applyOrElse(HttpTriplestoreConnector.scala:127)
api_1      | 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
api_1      | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.aroundReceive(HttpTriplestoreConnector.scala:64)
api_1      | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
api_1      | 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
api_1      | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
api_1      | 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api_1      | 	at java.base/java.lang.Thread.run(Unknown Source)
api_1      | 2020-02-24 00:43:38 | ERROR | Dispatcher | Couldn't parse Turtle from triplestore
api_1      | org.knora.webapi.TriplestoreResponseException: Couldn't parse Turtle from triplestore
api_1      | 	at org.knora.webapi.TriplestoreResponseException$.apply(Exceptions.scala:315)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:338)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$receive$1.applyOrElse(HttpTriplestoreConnector.scala:127)
api_1      | 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
api_1      | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.aroundReceive(HttpTriplestoreConnector.scala:64)
api_1      | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
api_1      | 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
api_1      | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
api_1      | 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api_1      | 	at java.base/java.lang.Thread.run(Unknown Source)
api_1      | Caused by: org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
api_1      | 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:276)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:690)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:685)
api_1      | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
api_1      | 	at scala.util.Failure.recover(Try.scala:234)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:685)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:331)
api_1      | 	... 11 common frames omitted
api_1      | Caused by: java.util.zip.ZipException: Not in GZIP format
api_1      | 	at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:69)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
api_1      | 	at java.base/java.io.InputStreamReader.read(Unknown Source)
api_1      | 	at java.base/java.io.Reader.read(Unknown Source)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:308)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getSparqlHttpResponse$1(HttpTriplestoreConnector.scala:664)
api_1      | 	at scala.util.Try$.apply(Try.scala:213)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:654)
api_1      | 	... 12 common frames omitted
api_1      | 2020-02-24 00:43:38 | ERROR | KnoraExceptionHandler$ | Unable to run route /v2/resources
api_1      | org.knora.webapi.TriplestoreResponseException: Couldn't parse Turtle from triplestore
api_1      | 	at org.knora.webapi.TriplestoreResponseException$.apply(Exceptions.scala:315)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:338)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$receive$1.applyOrElse(HttpTriplestoreConnector.scala:127)
api_1      | 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
api_1      | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.aroundReceive(HttpTriplestoreConnector.scala:64)
api_1      | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
api_1      | 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
api_1      | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
api_1      | 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api_1      | 	at java.base/java.lang.Thread.run(Unknown Source)
api_1      | Caused by: org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
api_1      | 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:276)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:690)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:685)
api_1      | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
api_1      | 	at scala.util.Failure.recover(Try.scala:234)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:685)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:331)
api_1      | 	... 11 common frames omitted
api_1      | Caused by: java.util.zip.ZipException: Not in GZIP format
api_1      | 	at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:69)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
api_1      | 	at java.base/java.io.InputStreamReader.read(Unknown Source)
api_1      | 	at java.base/java.io.Reader.read(Unknown Source)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:308)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getSparqlHttpResponse$1(HttpTriplestoreConnector.scala:664)
api_1      | 	at scala.util.Try$.apply(Try.scala:213)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:654)
api_1      | 	... 12 common frames omitted
api_1      | 2020-02-24 00:43:38 | ERROR | OneForOneStrategy | Couldn't parse Turtle from triplestore
api_1      | org.knora.webapi.TriplestoreResponseException: Couldn't parse Turtle from triplestore
api_1      | 	at org.knora.webapi.TriplestoreResponseException$.apply(Exceptions.scala:315)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:338)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$receive$1.applyOrElse(HttpTriplestoreConnector.scala:127)
api_1      | 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
api_1      | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.aroundReceive(HttpTriplestoreConnector.scala:64)
api_1      | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
api_1      | 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
api_1      | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
api_1      | 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api_1      | 	at java.base/java.lang.Thread.run(Unknown Source)
api_1      | Caused by: org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
api_1      | 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:276)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:690)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getSparqlHttpResponse$3.applyOrElse(HttpTriplestoreConnector.scala:685)
api_1      | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
api_1      | 	at scala.util.Failure.recover(Try.scala:234)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:685)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.org$knora$webapi$store$triplestore$http$HttpTriplestoreConnector$$sparqlHttpExtendedConstruct(HttpTriplestoreConnector.scala:331)
api_1      | 	... 11 common frames omitted
api_1      | Caused by: java.util.zip.ZipException: Not in GZIP format
api_1      | 	at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
api_1      | 	at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
api_1      | 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:69)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
api_1      | 	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
api_1      | 	at java.base/java.io.InputStreamReader.read(Unknown Source)
Is this what you are looking for?

api_1      | 	at java.base/java.io.Reader.read(Unknown Source)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
api_1      | 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:308)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getSparqlHttpResponse$1(HttpTriplestoreConnector.scala:664)
api_1      | 	at scala.util.Try$.apply(Try.scala:213)
api_1      | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.getSparqlHttpResponse(HttpTriplestoreConnector.scala:654)
api_1      | 	... 12 common frames omitted_

**Comment by benjamingeer** [comment] 2020-02-25 11:08
Yes, that's it. Very strange. It looks as if the triplestore returned a `Content-Encoding: gzip` header, but without returning a response in GZIP format.

**Comment by EricSommerhalder** [comment] 2020-02-25 13:17
Could that be a mistake on my side? Or is this an issue with knora-api?
________________________________
Von: Benjamin Geer <notifications@github.com>
Gesendet: Dienstag, 25. Februar 2020 12:08:11
An: dasch-swiss/knora-api
Cc: Eric Sommerhalder; Author
Betreff: Re: [dasch-swiss/knora-api] Upload memory issue using knora-py (#1605)


Yes, that's it. Very strange. It looks as if the triplestore returned a Content-Encoding: gzip header, but without returning a response in GZIP format.

**Comment by benjamingeer** [comment] 2020-02-25 13:21
My guess would be that it's a GraphDB bug, but I'll try to reproduce it and find out what's going wrong.

The JSON file you uploaded is actually an RTF file and looks like this:

```
{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf400
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
```

Please upload it again as a plain text file (you can use the extension `.json`).

Also please give more specific instructions for what to do with these files to reproduce the error, e.g. (1) Run script XYZ with these arguments, (2) run curl with these arguments...

**Comment by EricSommerhalder** [comment] 2020-02-26 11:55
This error is getting very weird. Even though I'm uploading the exact same json into a database with the exact same contents, no error is raised. Here what I'm doing:

1. Start knora-api with make stack-up 
2. Go to the GraphDB interface: http://0.0.0.0:7200
3. Go to import -> rdf and import the three trigs in the order of statements-3.trig, pou-admin-data.trig,  pou-permission-data.trig
4. Restart knora-api with make stack-up 
5. Run the attached python script, that uploads the problematic JSON that raised the error. Note that the scripts needs you to have knora.py installed

[reproduce_error.py.zip](https://github.com/dasch-swiss/knora-api/files/4255495/reproduce_error.py.zip)


However, this doesn't raise the error.

**Comment by benjamingeer** [comment] 2020-02-26 11:58
Thanks Eric, OK, so we have an intermittent problem. That suggests that maybe it really is related to something like memory use, which is not constant. We can try to reproduce it by running the same test multiple times to see if we can make the error occur after a while. Could you put a loop in `reproduce_error.py` and see what happens if it tries 100 times?

**Comment by EricSommerhalder** [comment] 2020-02-26 12:38
Did so, 100 went through trying with 10000. 
I'm attaching the original python script I used for the upload. The error is usually raised in line 303. The arrays in that area of the code can get quiet large. The error occured only in cases where these arrays where quiet large and a lot of create_resource-requests where posted. 
Could this be a reason for the error? 
[all_file_import.py.zip](https://github.com/dasch-swiss/knora-api/files/4255720/all_file_import.py.zip)

**Comment by benjamingeer** [comment] 2020-02-26 12:42
> Could this be a reason for the error?

I don't think this error has anything to do with `knora-py` or your Python code. It involves the communication between Knora and the triplestore: Knora makes an HTTP request to the triplestore, and the triplestore returns an unexpected response. I think we will have to send a bug report to GraphDB, but it's hard to do that if we can't reproduce the error.

**Comment by EricSommerhalder** [comment] 2020-02-26 18:13
Ok so the error occurs with a loop after approximately 
1530 iterations. However when I do another iteration after the program has failed, no error is raised. I have attached the python script with the loop.

[reproduce_error.py.zip](https://github.com/dasch-swiss/knora-api/files/4257450/reproduce_error.py.zip)

**Comment by subotic** [comment] 2020-02-27 05:33
> 4. Restart knora-api with make stack-up

To restart `knora` after loading data, please use `make stack-restart-api`.

**Comment by loicjaouen** [comment] 2020-02-27 09:06
just a few thoughts when getting these random errors on import, I first check:
- graphdb's repo settings (in the workbench) `Query time-out` and `Limit query results`
- knora to graphdb connection pool size, `KNORA_WEBAPI_DB_CONNECTIONS`

For small configs and large dataset, as a rule of thumb I would put `Query time-out` to 60s, `Limit query results` to 5000000 and `KNORA_WEBAPI_DB_CONNECTIONS` to 2.

**Comment by benjamingeer** [comment] 2020-02-27 09:38
@loicjaouen OK, but still, if there's a timeout somewhere, it shouldn't result in the error `Not in GZIP format`.

**Comment by benjamingeer** [comment] 2020-02-27 12:16
I'm unable to upload `statements-3.trig`: the upload never finishes, and a lot of error messages appear in the GraphDB workbench:

![Screenshot 2020-02-27 at 13 15 18](https://user-images.githubusercontent.com/558389/75444201-502d4580-5963-11ea-9382-e9bcaae6a35e.png)

Normally with a large file I would use the "Server Files" option, but I don't see how to do this if I'm running GraphDB in Docker. @subotic any ideas?

**Comment by benjamingeer** [comment] 2020-02-28 08:40
@subotic Since I can't import the test data into GraphDB in Docker (see above), I wanted to try this with GraphDB running outside of Docker, but for that I would need to be able to run Sipi, and and I can't because of #1614.

**Comment by loicjaouen** [comment] 2020-02-28 11:41
@benjamingeer 
- in the workbench, find the folder where the graphdb expect the (import -> RDF -> server files -> help) 
- copy the files using [docker cp](https://docs.docker.com/engine/reference/commandline/cp/)

**Comment by benjamingeer** [comment] 2020-02-28 11:45
@loicjaouen Thanks. Ivan told me that there's an environment variable, `KNORA_GDB_IMPORT`, described in the Knora README, that I can set so GraphDB in Docker will import files from the specified directory.

**Comment by benjamingeer** [comment] 2020-03-03 14:16
@subotic Using `KNORA_GDB_IMPORT`, I still can't import `statements-3.trig`. GraphDB seems to crash. The log says:

```
db_1       | The license key permits the use of GraphDB on systems with up to 1 CPU cores, but this Java Virtual Machine reports that 4 CPU cores are available.
db_1       | [INFO ] 2020-03-03 14:11:34,026 [import-task-knora-test-1 | c.o.r.p.ParallelRDFInserter] Importing stream
db_1       | [WARN ] 2020-03-03 14:11:34,044 [import-task-knora-test-1 | c.o.r.p.ParallelLoader] We were going to use 4 threads for inference but your license allows only 1, throttling applied
db_1       | [INFO ] 2020-03-03 14:11:44,029 [import-task-knora-test-1 | c.o.r.p.ParallelRDFInserter] Parsed 322,294 stmts. Rate: 32,226 st/s. Statements overall: 322,294. Global average rate: 32,222 st/s. Now: Tue Mar 03 14:11:44 UTC 2020. Total memory: 4929M, Free memory: 4064M, Max memory: 4929M.
docker_db_1 exited with code 137
```

Could you possibly try it and see if you get the same error?

**Comment by EricSommerhalder** [comment] 2020-03-03 17:41
I just ran into the same error again. I was able to fix it by simply running make stack-down followed by make stack-up

**Comment by benjamingeer** [comment] 2020-03-04 10:33
With GraphDB running outside of Docker, I can import the TriG files, but when I run `all_file_import.py`, I get this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'current_data/All renunciation of nationality cases_only_photographs_attached_11_02.csv'
```

**Comment by EricSommerhalder** [comment] 2020-03-05 11:25
Sorry, for that, of course you need the file. I adjusted the script a bit so you don't need other files as well. Please find attached the script as well as the file. 
[all_file_simplified.zip](https://github.com/dasch-swiss/knora-api/files/4292635/all_file_simplified.zip)

**Comment by benjamingeer** [comment] 2020-03-06 12:14
Thanks, but now I get:

```
FileNotFoundError: [Errno 2] No such file or directory: 'hicri_conversion_table.csv'
```

**Comment by EricSommerhalder** [comment] 2020-03-10 14:31
Ok, tried on my machine now, this should work now: 
[all_file_simplified.zip](https://github.com/dasch-swiss/knora-api/files/4312949/all_file_simplified.zip)

**Comment by benjamingeer** [comment] 2020-09-18 10:02
Closing because this seems to be a GraphDB issue, and we're not using GraphDB anymore.

**Closed by benjamingeer** 2020-09-18 10:02 UTC
Labels: blocking, clientapi, question
