### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1446] opened 2019-09-24 09:46 UTC
```bash
[info] Compiling 402 Scala sources to .../webapi/target/scala-2.12/classes ...
[warn] .../webapi/src/main/scala/org/knora/webapi/store/triplestore/embedded/JenaTDBActor.scala:441:49: class RAMDirectory in package store is deprecated: see corresponding Javadoc for more information.
[warn]             val indexDirectory: Directory = new RAMDirectory()
[warn]                                                 ^
[warn] .../webapi/src/main/scala/org/knora/webapi/store/triplestore/embedded/JenaTDBActor.scala:452:49: class RAMDirectory in package store is deprecated: see corresponding Javadoc for more information.
[warn]             val indexDirectory: Directory = new RAMDirectory()
[warn]                                                 ^
[warn] two warnings found

```

**Comment by benjamingeer** [comment] 2019-09-24 09:47
This is also fixed in #1403: https://github.com/dhlab-basel/Knora/pull/1403/files#diff-d36235129cdb679e49e12100b7f9e8d9

**Comment by subotic** [comment] 2019-09-24 09:51
Great, was easy to fix :-)

**Comment by tobiasschweizer** [comment] 2019-09-24 09:54
> This is also fixed in #1403: https://github.com/dhlab-basel/Knora/pull/1403/files#diff-d36235129cdb679e49e12100b7f9e8d9

Great! 

I think such fixes should rather be done in small and quick PRs since #1403 will be pending for a while. Or was it specifically related to #1403?

**Comment by benjamingeer** [comment] 2019-09-24 10:03
> Or was it specifically related to #1403?

It's caused by the upgrade of the RDF4J library in #1403.

**Comment by tobiasschweizer** [comment] 2019-09-24 10:08
> It's caused by the upgrade of the RDF4J library in #1403.

Was the upgrade of the RDF4J library specifically related to #1403? ;-)

**Comment by benjamingeer** [comment] 2019-09-24 10:10
> Was the upgrade of the RDF4J library specifically related to #1403? ;-)

Yes, it fixes a stack-overflow error in RDF4J which was triggered by adding a test in #1403.

**Comment by tobiasschweizer** [comment] 2019-09-24 10:12
Ok, got it. Thanks for the explanation!

**Comment by benjamingeer** [comment] 2019-09-24 11:41
... and the only reason you're getting the warning is because you copied the RDF4J upgrade from #1403.

**Closed** 2020-02-05 13:21 UTC
Labels: bug, stage/in-progress
