### ISSUE TITLE
Possible Groups-Admin bug

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/knora-api#1596] opened 2020-02-12 15:23 UTC
- Running the `knora-py` test triggers this error.

@lrosenth wrote:

The API call is:

http://0.0.0.0:3333/admin/users/iri/http%3A%2F%2Frdfh.ch%2Fusers%2FyKr4r0ZlRiq6ecihNEdfxw/group-memberships/http%3A%2F%2Frdfh.ch%2Fgroups%2F0001%2Fthing-searcher

Both the user and the project are existing....

Thanks,
	Lukas

```
rosenth@MacBook-Pro test % python3 -m unittest test_KnoraUser.py
.
E...
======================================================================
ERROR: test_KnoraUser_addToGroup (test_KnoraUser.TestKnoraUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rosenth/ProgDev/knora-py/test/test_KnoraUser.py", line 142, in test_KnoraUser_addToGroup
    nuser = user.update()
  File "/Users/rosenth/ProgDev/knora-py/knora/models/KnoraUser.py", line 630, in update
    result = self.con.post('/admin/users/iri/' + quote_plus(self._id) + '/group-memberships/' + quote_plus(p))
  File "/Users/rosenth/ProgDev/knora-py/knora/models/KnoraConnection.py", line 125, in post
    self.on_api_error(req)
  File "/Users/rosenth/ProgDev/knora-py/knora/models/KnoraConnection.py", line 93, in on_api_error
    raise KnoraError("KNORA-ERROR: status code=" + str(res.status_code) + "\nMessage:" + res.text)
models.KnoraConnection.KnoraError: KNORA-ERROR: status code=409
Message:{"error":"org.knora.webapi.UpdateNotPerformedException: User's 'group' memberships where not updated. Please report this as a possible bug."}

----------------------------------------------------------------------
Ran 5 tests in 9.096s

FAILED (errors=1)
r
```

**Comment by SepidehAlassi** [comment] 2020-09-15 11:19
@subotic & @lrosenth I just checked this issue. I could not regenerate the issue. The following call correctly adds the user to the group

POST: http://localhost:3333/admin/users/iri/http%3A%2F%2Frdfh.ch%2Fusers%2FBhkfBc3hTeS_IDo-JgXRbQ/group-memberships/http%3A%2F%2Frdfh.ch%2Fgroups%2F0001%2Fthing-searcher

This issue is pretty old. I believe the problem you are facing might have been fixed in the meantime, but the issue is not closed. I am closing it now, please reopen if you face the issue again.

**Closed by SepidehAlassi** 2020-09-15 11:19 UTC
Labels: bug
